name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

env:
  NODE_VERSION: '20.19.0'

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js 20.19+
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Build project
      working-directory: ./server
      run: npm run build
    
    - name: Run tests
      working-directory: ./server
      run: npm run test

  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js 20.19+
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Install dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Type check
      working-directory: ./client
      run: npm run type-check
    
    - name: Lint
      working-directory: ./client
      run: npm run lint
    
    - name: Build project
      working-directory: ./client
      run: npm run build
    
    - name: Run unit tests
      working-directory: ./client
      run: npm run test:unit
